Add `extensions` property to GraphQLError.
graphql-python/graphql-core-legacy pull request #204
Opened 2018-08-11 18:23 UTC by jckw

Allows an `extensions` property to be passed when creating a GraphQLError as described in https://github.com/graphql-python/graphql-core/issues/203. 

This property is included in [`graphql-js`](https://github.com/graphql/graphql-js/blob/master/src/error/GraphQLError.js#L30), which makes `graphql-python` more accurately reflect it.

2018-08-11 18:28 UTC, jckw commented
No idea why some tests are failing. Any help?

2018-09-10 19:05 UTC, nikordaris commented
Run tox locally and commit what it fixes. it will fix the formatting errors for you in the future if you install the pre-commit hook

2018-09-10 19:07 UTC, nikordaris commented
Also, you should probably add `extensions` to the slots list.

2018-09-10 20:24 UTC, nikordaris commented
Another problem with this is the `format_error` doesn't merge extensions from `original_error`. This is a common issue in my opinion with graphql-core. The executor wraps all raised errors in a `GraphQLLocatedError` which masks the original error in error reporting.

2019-03-06 21:00 UTC, dcosson commented
@jckw @nikordaris any chance of getting this merged to keep this library up to date with the graphql protocol?

2019-03-12 20:31 UTC, dan98765 requested changes
I've had to add 'extensions' as an override in our codebase since it's not in graphql-core yet.. so I'm also keen to see this feature merged. I do not see any tests added or updated so far. 
@jckw - could you please add/update test(s) that exercise the new code?

2019-04-29 17:57 UTC, nikordaris commented
I think we should close this PR in favor of https://github.com/graphql-python/graphql-core/pull/214 since it is passing the build and addresses the issues brought up in this PR

2021-03-01 09:26 UTC, jckw commented
Closed in favour of https://github.com/graphql-python/graphql-core-legacy/pull/214

2021-03-01 09:26 UTC, closed without merging