FIX #235: change RX requirements to a version below 3.0
graphql-python/graphql-core-legacy pull request #236
Opened 2019-03-27 15:55 UTC by Nabellaleen

Fix #235

2019-03-27 15:56 UTC, Nabellaleen commented
Maybe we should apply this fix to older graphql-core versions

2019-03-27 16:05 UTC, ProjectCheshire reviewed
Do we want to drop the greater than 1.6.0? I would assume we want gte 1.6.0 and lt 3.0.0

2019-03-27 18:23 UTC, dan98765 requested changes

2019-03-27 18:23 UTC, dan98765 commented on setup.py
> +install_requires = ["six>=1.10.0", "promise>=2.1", "rx<3.0.0"]
Same suggestion as @ProjectCheshire 
`1.6.0 >= rx < 3.0.0`

2019-03-28 03:45 UTC, SmileyChris commented on setup.py
> +install_requires = ["six>=1.10.0", "promise>=2.1", "rx<3.0.0"]
Using environment markers seems like the correct solution. There's no need to limit RX for people actually using Python 3 is there?
```suggestion
install_requires = [
    "six>=1.10.0",
    "promise>=2.1",
    'rx>=1.6.0,<3;python_version<"3"',
    'rx>=1.6.0;python_version>="3"',
]
```

2019-03-28 15:23 UTC, ProjectCheshire commented on setup.py
> +install_requires = ["six>=1.10.0", "promise>=2.1", "rx<3.0.0"]
Possibly out of scope of this PR, but brings up related dependencies amongst all the repos @dan98765 @SmileyChris

https://github.com/graphql-python/graphql-ws/blob/5f2cff5578b52f6c363567e5252d5e5d48e64787/graphql_ws/observable_aiter.py

Uses the extensionmethod that no longer exists in rx => 3, so the user python won't matter there

2019-07-17 21:15 UTC, jeremytubbs commented on setup.py
> +install_requires = ["six>=1.10.0", "promise>=2.1", "rx<3.0.0"]
```suggestion
install_requires = [
    "six>=1.10.0",
    "promise>=2.1",
    'rx>=1.6.0,<3;python_version<"3.6"',
    'rx>=1.6.0;python_version>="3.6"',
]
```

2019-07-18 16:58 UTC, Cito commented on setup.py
> +install_requires = ["six>=1.10.0", "promise>=2.1", "rx<3.0.0"]
I would keep the minimum requirement and make it "rx>=1.6,<3".

2019-07-18 17:00 UTC, jeremytubbs commented on setup.py
> +install_requires = ["six>=1.10.0", "promise>=2.1", "rx<3.0.0"]
I just know that this needs to be resolved... rx came out of Beta yesterday and is breaking installations.

2019-07-18 17:24 UTC, Cito commented on setup.py
> +install_requires = ["six>=1.10.0", "promise>=2.1", "rx<3.0.0"]
Ok, I will try to publish a new release as a hotfix.

2019-07-18 18:27 UTC, Cito commented on setup.py
> +install_requires = ["six>=1.10.0", "promise>=2.1", "rx<3.0.0"]
Hotfix release 2.2.1 is out now. Let me know if there are any problems with this release.

2019-07-18 18:28 UTC, Cito commented
Thank you all. This is now fixed in version 2.2.1.

2019-07-18 18:28 UTC, closed without merging